---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }}
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}
  ports:
  - port: 3306
    targetPort: 3306