---
{{/* 
Install secret only if this is a first installation 
*/}}
{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretsName }}
  namespace: {{ .Values.namespaceName  }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- include "wordpress.mysql.secrets" . | nindent 4 -}}
{{- end -}}